# Generated by Django 5.2.4 on 2025-07-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PecaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nome', models.TextField()),
                ('material', models.CharField(max_length=200)),
                ('espessura', models.CharField(max_length=50)),
                ('perimetro_mm', models.FloatField()),
                ('tempo_corte_segundos', models.FloatField()),
                ('peca_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpecas', to='uploadapi.pecaprincipal')),
            ],
        ),
    ]
